const readline = require("readline");
const fs = require("fs");


const data = [
  {
    date: "14-04-1991",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "09:51,90",
    alt_margin: "",
    margin: "02,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "22-04-1990",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:46,80",
    alt_margin: "",
    margin: "04,60",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "23-04-1989",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Okeanos",
    time: "10:17,80",
    alt_margin: "",
    margin: "12,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-04-1988",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:28,00",
    alt_margin: "",
    margin: "05,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-04-1987",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:01,30",
    alt_margin: "",
    margin: "10,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1986",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "00:00,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-04-1985",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "06:41,70",
    alt_margin: "",
    margin: "01,35",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-04-1984",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:16,40",
    alt_margin: "",
    margin: "03,31",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "15-04-1983",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "10:46,00",
    alt_margin: "",
    margin: "06,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-04-1982",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:13,50",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1981",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "09:50,50",
    alt_margin: "",
    margin: "01,12",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-04-1980",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "09:59,50",
    alt_margin: "",
    margin: "05,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1979",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:49,20",
    alt_margin: "",
    margin: "07,70",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-04-1978",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:02,00",
    alt_margin: "",
    margin: "02,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1977",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:25,00",
    alt_margin: "",
    margin: "07,40",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1976",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:07,00",
    alt_margin: "",
    margin: "17,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1975",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "11:13,80",
    alt_margin: "",
    margin: "14,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1974",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:21,60",
    alt_margin: "",
    margin: "02,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1973",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:57,00",
    alt_margin: "",
    margin: "00,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1972",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:19,50",
    alt_margin: "",
    margin: "44,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1971",
    location: "Boschbaan",
    club: "Nereus",
    time: "07:15,00",
    alt_margin: "",
    margin: "06,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1970",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:55,60",
    alt_margin: "",
    margin: "08,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1969",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:32,40",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1968",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "10:40,90",
    alt_margin: "",
    margin: "02,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1967",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:18,00",
    alt_margin: "",
    margin: "18,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1966",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "11:16,80",
    alt_margin: "",
    margin: "20,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1965",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:28,80",
    alt_margin: "",
    margin: "05,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1964",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:17,20",
    alt_margin: "",
    margin: "00,60",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1963",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:42,80",
    alt_margin: "",
    margin: "00,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1962",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:58,50",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1961",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Argo",
    time: "10:32,60",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1960",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Ar/Njo",
    time: "10:35,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1959",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "11:10,80",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1958",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:59,80",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1957",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:42,50",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1956",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Aegir",
    time: "10:36,80",
    alt_margin: "",
    margin: "00,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1955",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:08,20",
    alt_margin: "",
    margin: "03,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1954",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "11:49,80",
    alt_margin: "1 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1953",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:45,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1952",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:54,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1951",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:43,60",
    alt_margin: "1/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1950",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:43,60",
    alt_margin: "",
    margin: "00,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1949",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:48,40",
    alt_margin: "6 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1948",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "10:53,40",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1947",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "10:47,40",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1946",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:12,00",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1940",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:05,00",
    alt_margin: "10 cm",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "18-05-1939",
    location: "Boschbaan",
    club: "Laga",
    time: "07:23,80",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "15-05-1938",
    location: "Boschbaan",
    club: "Laga",
    time: "07:10,50",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1937",
    location: "Boschbaan",
    club: "Triton",
    time: "06:57,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1936",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "12:21,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1935",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:13,20",
    alt_margin: "1 1/3",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "10-05-1934",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "12:13,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1933",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "10:49,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1932",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "10:36,00",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "14-05-1931",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:04,20",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "11-05-1930",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "11:21,00",
    alt_margin: "1 meter",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-05-1929",
    location: "Noordzeekanaal",
    club: "Njord",
    time: "11:11,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "17-05-1928",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:06,00",
    alt_margin: "taftlengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1927",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:03,00",
    alt_margin: "1 meter",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1926",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:10,80",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1925",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "10:44,80",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "11-05-1924",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "10:45,60",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "10-05-1923",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "10:54,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1922",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:37,60",
    alt_margin: "1 3/4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1921",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:51,80",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1920",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:22,00",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1919",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:40,00",
    alt_margin: "1 1/4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1918",
    location: "Noordzeekanaal",
    club: "Aegir",
    time: "13:25,00",
    alt_margin: "6 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "17-05-1917",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "14:39,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-06-1916",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:54,80",
    alt_margin: "taftlengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1915",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "09:45,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1914",
    location: "De Schie",
    club: "Laga",
    time: "11:31,00",
    alt_margin: "4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "12-05-1913",
    location: "De Schie",
    club: "Laga",
    time: "12:05,60",
    alt_margin: "5",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1912",
    location: "De Schie",
    club: "Triton",
    time: "11:40,00",
    alt_margin: "gemakkelijk",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1911",
    location: "De Schie",
    club: "Triton",
    time: "12:32,00",
    alt_margin: "5",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1910",
    location: "De Schie",
    club: "Nereus",
    time: "12:21,00",
    alt_margin: "",
    margin: "14,8",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1909",
    location: "De Schie",
    club: "Nereus",
    time: "11:37,50",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1908",
    location: "De Schie",
    club: "Njord",
    time: "12:05,00",
    alt_margin: "4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1907",
    location: "De Schie",
    club: "Laga",
    time: "12:18,00",
    alt_margin: "1",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1906",
    location: "De Schie",
    club: "Njord",
    time: "12:16,00",
    alt_margin: "16",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1905",
    location: "De Schie",
    club: "Nereus",
    time: "11:56,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-06-1904",
    location: "De Schie",
    club: "Nereus",
    time: "11:20,00",
    alt_margin: "gemakkelijk",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1903",
    location: "De Schie",
    club: "Laga",
    time: "11:00,00",
    alt_margin: "1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "04-06-1902",
    location: "De Schie",
    club: "Laga",
    time: "11:02,50",
    alt_margin: "1",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-06-1901",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "12:40,00",
    alt_margin: "5 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1900",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "10:25,00",
    alt_margin: "1/3 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-05-1899",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:29,00",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1898",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "11:15,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-06-1897",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:52,20",
    alt_margin: "",
    margin: "08,75",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1896",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:51,40",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1895",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:55,00",
    alt_margin: "10 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1894",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:39,00",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "04-06-1893",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:08,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "29-05-1892",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "13:28,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1891",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "12:43,00",
    alt_margin: "",
    margin: "03,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-06-1890",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "14:00,00",
    alt_margin: "",
    margin: "14,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-05-1889",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "13:49,00",
    alt_margin: "",
    margin: "15,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1888",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "12:54,60",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "22-05-1887",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "14:00,00",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1886",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "14:36,00",
    alt_margin: "",
    margin: "08,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1885",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "15:24,00",
    alt_margin: "",
    margin: "18,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-10-1884",
    location: "Oude Rijn",
    club: "Njord",
    time: "14:07,00",
    alt_margin: "",
    margin: "04,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-06-1883",
    location: "Oude Rijn",
    club: "Njord",
    time: "00:00,00",
    alt_margin: "--",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-10-1882",
    location: "Galgewater",
    club: "Njord",
    time: "15:22,00",
    alt_margin: "",
    margin: "37,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-10-1881",
    location: "De Schie",
    club: "Laga",
    time: "00:00,00",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-06-1880",
    location: "Galgewater",
    club: "Laga",
    time: "15:14,00",
    alt_margin: "",
    margin: "15,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-07-1878",
    location: "Galgewater",
    club: "Laga",
    time: "14:42,00",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
];

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function askQuestion(query) {
    return new Promise(resolve => rl.question(query, resolve));
}

const outFile = "main.json";

async function main() {
    for (let i = 0; i < data.length; i++)
    {
        let current = data[i];


        console.log(current.date);
        
        current.crew[0] = { name: await askQuestion("bow: ") };
        current.crew[1] = { name: await askQuestion("3: ") };
        current.crew[2] = { name: await askQuestion("2: ") };
        current.crew[3] = { name: await askQuestion("stroke: ") };
        current.crew[4] = { name: await askQuestion("cox: ") };

        fs.appendFileSync(outFile, JSON.stringify(current) + ",", (err) => {
            if (err) {
                console.error('Error writing to file:', err);
            } else {
                console.log(`Text has been written to ${outFile}`);
            }
        });

        console.log("\n");

    }
}

main();
