const strings = [
  "2 jul 1878 Leiden 3200 Laga 14:42 12 sec",
  "13 jun 1880 Leiden 3200 Laga 15:14 15 sec",
  "9 okt 1881 Delft 3400 Laga -- 12 sec",
  "9 okt 1882 Leiden 3600 Njord 15:22 37 sec",
  "30 jun 1883 Oudshoorn 3400 Njord -- --",
  "5 okt 1884 Oudshoorn 3400 Njord 14:07 04 sec",
  "31 mei 1885 Haarlem 3400 Njord 15:24 18 sec",
  "30 mei 1886 Haarlem 3400 Njord 14:36 08 sec",
  "22 mei 1887 Haarlem 3400 Njord 14:00 09 sec",
  "27 mei 1888 Haarlem 3400 Laga 12:54,6 12 sec",
  "26 mei 1889 Haarlem 3400 Njord 13:49 15 sec",
  "1 jun 1890 Haarlem 3300 Laga 14:00 14,5 sec",
  "31 mei 1891 Haarlem 3000 Nereus 12:43 3 sec",
  "29 mei 1892 Haarlem 3000 Nereus 13:28 ?",
  "4 jun 1893 Haarlem 3000 Nereus 11:08 2 lengten",
  "27 mei 1894 Haarlem 3000 Nereus 11:39 1/2 lengte",
  "28 mei 1895 Haarlem 3000 Triton 10:55 10 lengten",
  "31 mei 1896 Haarlem 3000 Triton 10:51,4 4 lengten",
  "7 jun 1897 Haarlem 3000 Triton 10:52,2 8,75 sec",
  "30 mei 1898 Haarlem 3000 Triton 11:15,6 2 lengten",
  "26 mei 1899 Haarlem 3000 Nereus 11:29 9 sec",
  "27 mei 1900 Haarlem 3000 Njord 10:25 1/3 lengte",
  "2 jun 1901 Haarlem 3000 Laga 12:40 5 lengten",
  "4 jun 1902 De Zweth 3000 Laga 11:02,5 1",
  "24 mei 1903 De Zweth 3000 Laga 11:00 1/2",
  "5 jun 1904 De Zweth 3000 Nereus 11:20 gemakkelijk",
  "28 mei 1905 De Zweth 3000 Nereus 11:56 ?",
  "24 mei 1906 De Zweth 3000 Njord 12:16 16",
  "20 mei 1907 De Zweth 3000 Laga 12:18 1",
  "28 mei 1908 De Zweth 3000 Njord 12:05 4",
  "20 mei 1909 De Zweth 3000 Nereus 11:37,5 ?",
  "16 mei 1910 De Zweth 3000 Nereus 12:21 14,8",
  "25 mei 1911 De Zweth 3000 Triton 12:32 5",
  "16 mei 1912 De Zweth 3000 Triton 11:40 gemakkelijk",
  "12 mei 1913 De Zweth 3000 Laga 12:05,6 5",
  "21 mei 1914 De Zweth 3000 Laga 11:31 4",
  "13 mei 1915 Nrdzeekan. 2000 Laga 9:45 2 lengten",
  "1 jun 1916 Nrdzeekan. 3000 Nereus 11:54,8 taftlengte",
  "17 mei 1917 Nrdzeekan. 3000 Laga 14:39 2 1/2",
  "20 mei 1918 Nrdzeekan. 3000 Aegir 13:25 6 lengten",
  "25 mei 1919 Nrdzeekan. 3000 Nereus 11:40 1 1/4",
  "13 mei 1920 Nrdzeekan. 3000 Laga 11:22 1 1/2",
  "5 mei 1921 Nrdzeekan. 3000 Nereus 11:51,8 1/2 lengte",
  "25 mei 1922 Nrdzeekan. 3000 Laga 11:37,6 1 3/4",
  "10 mei 1923 Nrdzeekan. 3000 Laga 10:54,6 2 lengten",
  "11 mei 1924 Nrdzeekan. 3000 Nereus 10:45,6 1/2 lengte",
  "21 mei 1925 Nrdzeekan. 3000 Laga 10:44,8 ?",
  "13 mei 1926 Nrdzeekan. 3000 Laga 11:10,8 1/2 lengte",
  "28 mei 1927 Nrdzeekan. 3000 Laga 11:03 1 meter",
  "17 mei 1928 Nrdzeekan. 3000 Nereus 11:06 taftlengte",
  "9 mei 1929 Nrdzeekan. 3000 Njord 11:11 3/4 lengte",
  "11 mei 1930 Nrdzeekan. 3000 Triton 11:21 1 meter",
  "14 mei 1931 Nrdzeekan. 3000 Nereus 11:04,2 2 lengten",
  "5 mei 1932 Nrdzeekan. 3000 Nereus 10:36 1 1/2",
  "25 mei 1933 Nrdzeekan. 3000 Triton 10:49,6 2 lengten",
  "10 mei 1934 Nrdzeekan. 3000 Nereus 12:13 3/4 lengte",
  "30 mei 1935 Nrdzeekan. 3000 Nereus 11:13,2 1 1/3",
  "21 mei 1936 Nrdzeekan. 3000 Triton 12:21 2 lengten",
  "6 mei 1937 Bosbaan 2000 Triton 6:57 3/4 lengte",
  "15 mei 1938 Bosbaan 2000 Laga 7:10,5 3/4 lengte",
  "18 mei 1939 Bosbaan 2000 Laga 7:23,8 2 1/2",
  "5 mei 1940 Juthphaas 3000 Laga 11:05 10 cm",
  "5 mei 1946 Juthphaas 3000 Triton 11:12 4 lengten",
  "1 mei 1947 Juthphaas 3000 Triton 10:47,4 3/4 lengte",
  "2 mei 1948 Juthphaas 3000 Triton 10:53,4 3/4 lengte",
  "1 mei 1949 Juthphaas 3000 Njord 10:48,4 6 lengten",
  "7 mei 1950 Juthphaas 3000 Njord 10:43,6 0,2 sec",
  "6 mei 1951 Juthphaas 3000 Njord 10:43,6 1/4 lengte",
  "27 apr 1952 Juthphaas 3000 Nereus 10:54 2 1/2",
  "3 mei 1953 Juthphaas 3000 Nereus 10:45 2 1/2",
  "2 mei 1954 Juthphaas 3000 Njord 11:49,8 1 lengte",
  "1 mei 1955 Juthphaas 3000 Laga 11:08,2 3,8 sec",
  "6 mei 1956 Juthphaas 3000 Aegir 10:36,8 0,5 sec",
  "5 mei 1957 Juthphaas 3000 Laga 11:42,5 1 1/2",
  "27 apr 1958 Juthphaas 3000 Nereus 10:59,8 2 1/2",
  "3 mei 1959 Juthphaas 3000 Nereus 11:10,8 2 lengten",
  "1 mei 1960 Juthphaas 3000 Ar/Njo 10:35,6 2 lengten",
  "16 mei 1961 Juthphaas 3000 Argo 10:32,6 4 lengten",
  "6 mei 1962 Juthphaas 3000 Nereus 10:58,5 1/2 lengte",
  "6 mei 1963 Juthphaas 3000 Njord 10:42,8 0,5 sec",
  "24 mei 1964 Juthphaas 3000 Triton 11:17,2 0,6 sec",
  "2 mei 1965 Juthphaas 3000 Nereus 10:28,8 5,3 sec",
  "1 mei 1966 Juthphaas 3000 Nereus 11:16,8 20,8 sec",
  "7 mei 1967 Juthphaas 3000 Triton 11:18 18 sec",
  "5 mei 1968 Juthphaas 3000 Laga 10:40,9 2,1 sec",
  "27 apr 1969 Juthphaas 3000 Nereus 10:32,4 9 sec",
  "3 mei 1970 Houten 3000 Laga 10:55,6 8 sec",
  "2 mei 1971 Bosbaan 2000 Nereus 7:15,0 6 sec",
  "7 mei 1972 Houten 3000 Laga 10:19,5 44 sec",
  "6 mei 1973 Houten 3000 Laga 10:57,0 0,8 sec",
  "5 mei 1974 Houten 3000 Aegir 10:21,6 2,2 sec",
  "27 apr 1975 Houten 3000 Aegir 11:13,8 14,1 sec",
  "2 mei 1976 Houten 3000 Laga 10:07,0 17 sec",
  "1 mei 1977 Houten 3000 Nereus 10:25,0 7,4 sec",
  "16 apr 1978 Houten 3000 Aegir 10:02,0 2,8 sec",
  "27 apr 1979 Houten 3000 Nereus 10:49,2 7,7 sec",
  "26 apr 1980 Houten 3000 Orca 9:59,5 5,8 sec",
  "2 mei 1981 Houten 3000 Skadi 9:50,5 1,12 sec",
  "24 apr 1982 Houten 3000 Aegir 10:13,5 ? ?",
  "15 apr 1983 Houten 3000 Orca 10:46 6 sec",
  "28 apr 1984 Houten 3000 Njord 10:16,4 3,31 sec",
  "28 apr 1985 Houten 2000 Njord 6:41,7 1,35 sec",
  "27 apr 1986 Houten 3000 Njord ? ?",
  "26 apr 1987 Houten 3000 Njord 10:01,3 10,3 sec",
  "24 apr 1988 Houten 3000 Njord 10:28 5 sec",
  "23 apr 1989 Houten 3000 Okeanos 10:17,8 12,8 sec",
  "22 apr 1990 Houten 3000 Laga 10:46,8 4,6 sec",
  "14 apr 1991 Houten 3000 Nereus 9:51,9 2,3 sec",
  "19 apr 1992 Houten 3000 Skadi 9:28,0 1 sec",
  "18 apr 1993 Houten 3000 Nereus 10:02,0 5,04 sec",
  "17 apr 1994 Houten 3000 Nereus 10:07,5 10,2 sec",
  "23 apr 1995 Houten 3000 Euros 9:55,1 2,8 sec",
  "14 apr 1996 Houten 3000 Nereus 10:22,8 11 sec",
  "13 apr 1997 Houten 3000 Laga 9:40,5 4,4 sec",
  "19 apr 1998 Houten 3000 Nereus 9:58,9 8,1 sec",
  "18 apr 1999 Houten 3000 Orca 9:31,2 1,8 sec",
  "16 apr 2000 Houten 3000 Orca 10:19,0 6,8 sec",
  "8 apr 2001 Houten 3000 Skadi 9:58,6 7,1 sec",
  "7 apr 2002 Houten 3000 Nereus 10:09,0 8,2 sec",
  "13 apr 2003 Houten 3000 Nereus 10:56,2 5,5 sec",
  "11 apr 2004 Houten 3000 Orca 10:00,8 4,9 sec",
  "10 apr 2005 Houten 3000 Nereus 9:59,9 1,4 sec",
  "9 apr 2006 Houten 3000 Skadi 9:39,7 5,2 sec",
  "15 apr 2007 Houten 3000 Skadi 10:08,7 5,2 sec",
];

function monthToInt(month) {
  switch (month) {
    case "apr":
      return "04";
    case "mei":
      return "05";
    case "okt":
      return "10";
    case "jun":
      return "06";
    case "jul":
      return "07";
    default:
      return "###########";
  }
}

function consistentTime(time) {
  if (time === "?" || time.indexOf("-") !== -1) return "00:00,00";
  let out = "";
  let p = time.split(":");
  if (p[0].length == 2) out += p[0];
  else out += `0${p[0]}`;
  out += ":";

  let commap = p[1].split(",");

  if (commap[0].length == 2) out += commap[0];
  else out += `0${commap[0]}`;

  if (commap.length == 1) out += ",00";
  else out += `,${commap[1]}0`;

  return out;
}

function consistentSec(sec) {
  let out = "";
  let p = sec.split(",");
  if (p[0].length == 1) out += "0" + p[0];
  else out += p[0];
  out += ",";
  if (p[1].length == 1) out += p[1] + "0";
  else out += p[1];
  return out;
}

function consistentMargin(margin) {
  if (margin.indexOf("?") > -1) return "00,00";
  let out = "";
  if (margin.indexOf("sec") > -1) {
    let sec = margin.split(" ")[0];

    // consistent seconds
    if (sec.indexOf(",") == -1) out += consistentSec(`${sec},00`);
    else out += consistentSec(sec);

    return out;
  } else return margin;
}

function morphLocation(location) {
  switch (location) {
    case "Houten":
      return "Amsterdam-Rijnkanaal (Houten)";
    case "Juthphaas":
      return "Amsterdam-Rijnkanaal (Jutphaas)";
    case "Bosbaan":
      return "Boschbaan";
    case "Nrdzeekan.":
      return "Noordzeekanaal";
    case "Haarlem":
      return "Noorder-Buitenspaarne";
    case "Oudshoorn":
      return "Oude Rijn";
    case "Leiden":
      return "Galgewater";
    case "Delft":
      return "De Schie";
    case "De Zweth":
      return "De Schie";
  }
}

let arr = [];

for (let i = strings.length - 1; i >= 0; i--) {
  let str = strings[i];

  let parts = str.split(" ");
  // console.log(parts);

  let date = `${parts[0].length == 2 ? parts[0] : `0${parts[0]}`}-${monthToInt(
    parts[1]
  )}-${parts[2]}`;
  // console.log(date);

  let zwethFlag = parts[3] == "De";
  let location = zwethFlag ? parts[3] + " " + parts[4] : parts[3];
  location = morphLocation(location);
  // console.log(location);

  let length = zwethFlag ? parts[5] : parts[4];
  // console.log(length);

  let club = zwethFlag ? parts[6] : parts[5];
  // console.log(club);

  let time = zwethFlag ? parts[7] : parts[6];
  time = consistentTime(time);
  // console.log(time);

  let margin = zwethFlag ? parts.slice(8).join(" ") : parts.slice(7).join(" ");
  margin = consistentMargin(margin);
  // console.log(margin);

  let obj = {
    date: date,
    location: location,
    club: club,
    time: time,
    alt_margin: margin.indexOf(",") < 0 ? margin : "",
    margin: margin.indexOf(",") < 0 ? "00,00" : margin,
    crew: [
      {
        name: "",
      },
      {
        name: "",
      },
      {
        name: "",
      },
      {
        name: "",
      },
      {
        name: "",
      },
    ],
    notes: "",
    sources: [25, 28],
  };

  arr.push(obj);
}

console.log(JSON.stringify(arr));

[
  {
    date: "15-04-2007",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "10:08,70",
    alt_margin: "",
    margin: "05,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-04-2006",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "09:39,70",
    alt_margin: "",
    margin: "05,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "10-04-2005",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "09:59,90",
    alt_margin: "",
    margin: "01,40",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "11-04-2004",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "10:00,80",
    alt_margin: "",
    margin: "04,90",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-04-2003",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:56,20",
    alt_margin: "",
    margin: "05,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-04-2002",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:09,00",
    alt_margin: "",
    margin: "08,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "08-04-2001",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "09:58,60",
    alt_margin: "",
    margin: "07,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-04-2000",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "10:19,00",
    alt_margin: "",
    margin: "06,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "18-04-1999",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "09:31,20",
    alt_margin: "",
    margin: "01,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "19-04-1998",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "09:58,90",
    alt_margin: "",
    margin: "08,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-04-1997",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "09:40,50",
    alt_margin: "",
    margin: "04,40",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "14-04-1996",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:22,80",
    alt_margin: "",
    margin: "11,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "23-04-1995",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Euros",
    time: "09:55,10",
    alt_margin: "",
    margin: "02,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "17-04-1994",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:07,50",
    alt_margin: "",
    margin: "10,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "18-04-1993",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:02,00",
    alt_margin: "",
    margin: "05,04",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "19-04-1992",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "09:28,00",
    alt_margin: "",
    margin: "01,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "14-04-1991",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "09:51,90",
    alt_margin: "",
    margin: "02,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "22-04-1990",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:46,80",
    alt_margin: "",
    margin: "04,60",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "23-04-1989",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Okeanos",
    time: "10:17,80",
    alt_margin: "",
    margin: "12,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-04-1988",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:28,00",
    alt_margin: "",
    margin: "05,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-04-1987",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:01,30",
    alt_margin: "",
    margin: "10,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1986",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "00:00,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-04-1985",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "06:41,70",
    alt_margin: "",
    margin: "01,35",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-04-1984",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Njord",
    time: "10:16,40",
    alt_margin: "",
    margin: "03,31",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "15-04-1983",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "10:46,00",
    alt_margin: "",
    margin: "06,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-04-1982",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:13,50",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1981",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Skadi",
    time: "09:50,50",
    alt_margin: "",
    margin: "01,12",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-04-1980",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Orca",
    time: "09:59,50",
    alt_margin: "",
    margin: "05,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1979",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:49,20",
    alt_margin: "",
    margin: "07,70",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-04-1978",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:02,00",
    alt_margin: "",
    margin: "02,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1977",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Nereus",
    time: "10:25,00",
    alt_margin: "",
    margin: "07,40",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1976",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:07,00",
    alt_margin: "",
    margin: "17,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1975",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "11:13,80",
    alt_margin: "",
    margin: "14,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1974",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Aegir",
    time: "10:21,60",
    alt_margin: "",
    margin: "02,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1973",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:57,00",
    alt_margin: "",
    margin: "00,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1972",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:19,50",
    alt_margin: "",
    margin: "44,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1971",
    location: "Boschbaan",
    club: "Nereus",
    time: "07:15,00",
    alt_margin: "",
    margin: "06,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1970",
    location: "Amsterdam-Rijnkanaal (Houten)",
    club: "Laga",
    time: "10:55,60",
    alt_margin: "",
    margin: "08,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1969",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:32,40",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1968",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "10:40,90",
    alt_margin: "",
    margin: "02,10",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1967",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:18,00",
    alt_margin: "",
    margin: "18,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1966",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "11:16,80",
    alt_margin: "",
    margin: "20,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1965",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:28,80",
    alt_margin: "",
    margin: "05,30",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1964",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:17,20",
    alt_margin: "",
    margin: "00,60",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1963",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:42,80",
    alt_margin: "",
    margin: "00,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1962",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:58,50",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1961",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Argo",
    time: "10:32,60",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1960",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Ar/Njo",
    time: "10:35,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1959",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "11:10,80",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1958",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:59,80",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1957",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:42,50",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1956",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Aegir",
    time: "10:36,80",
    alt_margin: "",
    margin: "00,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1955",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:08,20",
    alt_margin: "",
    margin: "03,80",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1954",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "11:49,80",
    alt_margin: "1 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "03-05-1953",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:45,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-04-1952",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Nereus",
    time: "10:54,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1951",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:43,60",
    alt_margin: "1/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-05-1950",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:43,60",
    alt_margin: "",
    margin: "00,20",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1949",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Njord",
    time: "10:48,40",
    alt_margin: "6 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-05-1948",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "10:53,40",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-05-1947",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "10:47,40",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1946",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Triton",
    time: "11:12,00",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1940",
    location: "Amsterdam-Rijnkanaal (Jutphaas)",
    club: "Laga",
    time: "11:05,00",
    alt_margin: "10 cm",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "18-05-1939",
    location: "Boschbaan",
    club: "Laga",
    time: "07:23,80",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "15-05-1938",
    location: "Boschbaan",
    club: "Laga",
    time: "07:10,50",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "06-05-1937",
    location: "Boschbaan",
    club: "Triton",
    time: "06:57,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1936",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "12:21,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1935",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:13,20",
    alt_margin: "1 1/3",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "10-05-1934",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "12:13,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1933",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "10:49,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1932",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "10:36,00",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "14-05-1931",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:04,20",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "11-05-1930",
    location: "Noordzeekanaal",
    club: "Triton",
    time: "11:21,00",
    alt_margin: "1 meter",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-05-1929",
    location: "Noordzeekanaal",
    club: "Njord",
    time: "11:11,00",
    alt_margin: "3/4 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "17-05-1928",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:06,00",
    alt_margin: "taftlengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1927",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:03,00",
    alt_margin: "1 meter",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1926",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:10,80",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1925",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "10:44,80",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "11-05-1924",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "10:45,60",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "10-05-1923",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "10:54,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1922",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:37,60",
    alt_margin: "1 3/4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-05-1921",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:51,80",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1920",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "11:22,00",
    alt_margin: "1 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1919",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:40,00",
    alt_margin: "1 1/4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1918",
    location: "Noordzeekanaal",
    club: "Aegir",
    time: "13:25,00",
    alt_margin: "6 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "17-05-1917",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "14:39,00",
    alt_margin: "2 1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-06-1916",
    location: "Noordzeekanaal",
    club: "Nereus",
    time: "11:54,80",
    alt_margin: "taftlengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-05-1915",
    location: "Noordzeekanaal",
    club: "Laga",
    time: "09:45,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "21-05-1914",
    location: "De Schie",
    club: "Laga",
    time: "11:31,00",
    alt_margin: "4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "12-05-1913",
    location: "De Schie",
    club: "Laga",
    time: "12:05,60",
    alt_margin: "5",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1912",
    location: "De Schie",
    club: "Triton",
    time: "11:40,00",
    alt_margin: "gemakkelijk",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "25-05-1911",
    location: "De Schie",
    club: "Triton",
    time: "12:32,00",
    alt_margin: "5",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "16-05-1910",
    location: "De Schie",
    club: "Nereus",
    time: "12:21,00",
    alt_margin: "",
    margin: "14,8",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1909",
    location: "De Schie",
    club: "Nereus",
    time: "11:37,50",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1908",
    location: "De Schie",
    club: "Njord",
    time: "12:05,00",
    alt_margin: "4",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "20-05-1907",
    location: "De Schie",
    club: "Laga",
    time: "12:18,00",
    alt_margin: "1",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1906",
    location: "De Schie",
    club: "Njord",
    time: "12:16,00",
    alt_margin: "16",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1905",
    location: "De Schie",
    club: "Nereus",
    time: "11:56,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-06-1904",
    location: "De Schie",
    club: "Nereus",
    time: "11:20,00",
    alt_margin: "gemakkelijk",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "24-05-1903",
    location: "De Schie",
    club: "Laga",
    time: "11:00,00",
    alt_margin: "1/2",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "04-06-1902",
    location: "De Schie",
    club: "Laga",
    time: "11:02,50",
    alt_margin: "1",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-06-1901",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "12:40,00",
    alt_margin: "5 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1900",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "10:25,00",
    alt_margin: "1/3 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-05-1899",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:29,00",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1898",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "11:15,60",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "07-06-1897",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:52,20",
    alt_margin: "",
    margin: "08,75",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1896",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:51,40",
    alt_margin: "4 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "28-05-1895",
    location: "Noorder-Buitenspaarne",
    club: "Triton",
    time: "10:55,00",
    alt_margin: "10 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1894",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:39,00",
    alt_margin: "1/2 lengte",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "04-06-1893",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "11:08,00",
    alt_margin: "2 lengten",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "29-05-1892",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "13:28,00",
    alt_margin: "",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1891",
    location: "Noorder-Buitenspaarne",
    club: "Nereus",
    time: "12:43,00",
    alt_margin: "",
    margin: "03,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "01-06-1890",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "14:00,00",
    alt_margin: "",
    margin: "14,50",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "26-05-1889",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "13:49,00",
    alt_margin: "",
    margin: "15,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "27-05-1888",
    location: "Noorder-Buitenspaarne",
    club: "Laga",
    time: "12:54,60",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "22-05-1887",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "14:00,00",
    alt_margin: "",
    margin: "09,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-05-1886",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "14:36,00",
    alt_margin: "",
    margin: "08,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "31-05-1885",
    location: "Noorder-Buitenspaarne",
    club: "Njord",
    time: "15:24,00",
    alt_margin: "",
    margin: "18,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "05-10-1884",
    location: "Oude Rijn",
    club: "Njord",
    time: "14:07,00",
    alt_margin: "",
    margin: "04,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "30-06-1883",
    location: "Oude Rijn",
    club: "Njord",
    time: "00:00,00",
    alt_margin: "--",
    margin: "00,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-10-1882",
    location: "Galgewater",
    club: "Njord",
    time: "15:22,00",
    alt_margin: "",
    margin: "37,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "09-10-1881",
    location: "De Schie",
    club: "Laga",
    time: "00:00,00",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "13-06-1880",
    location: "Galgewater",
    club: "Laga",
    time: "15:14,00",
    alt_margin: "",
    margin: "15,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
  {
    date: "02-07-1878",
    location: "Galgewater",
    club: "Laga",
    time: "14:42,00",
    alt_margin: "",
    margin: "12,00",
    crew: [
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
      { name: "" },
    ],
    notes: "",
    sources: [25, 28],
  },
];
